
<select class="form-control" name="{{ $name }}" id="{{ $name }}" required="required" @if(isset($vue)) v-model="{{ $vue }}" @endif >
	<option value="Afghanistan" @if(isset($value) && $value=='Afghanistan') selected="true" @endif> Afghanistan </option>
	<option value="African-Union(OAS)" @if(isset($value) && $value=='African-Union(OAS)') selected="true" @endif> African-Union(OAS)  </option>
	<option value="Albania" @if(isset($value) && $value=='Albania') selected="true" @endif>  Albania </option>
	<option value="Algeria" @if(isset($value) && $value=='Algeria') selected="true" @endif>  Algeria </option>
	<option value="American-Samoa" @if(isset($value) && $value=='American-Samoa') selected="true" @endif> American-Samoa  </option>
	<option value="Andorra" @if(isset($value) && $value=='Andorra') selected="true" @endif>  Andorra </option>
	<option value="Angola" @if(isset($value) && $value=='Angola') selected="true" @endif> Angola  </option>
	<option value="Anguilla" @if(isset($value) && $value=='Anguilla') selected="true" @endif> Anguilla  </option>
	<option value="Antarctica" @if(isset($value) && $value=='Antarctica') selected="true" @endif> Antarctica  </option>
	<option value="Antigua-Barbuda" @if(isset($value) && $value=='Antigua-Barbuda') selected="true" @endif>  Antigua-Barbuda </option>
	<option value="Arab-League" @if(isset($value) && $value=='Arab-League') selected="true" @endif>  Arab-League </option>
	<option value="Argentina" @if(isset($value) && $value=='Argentina') selected="true" @endif>  Argentina </option>
	<option value="Armenia" @if(isset($value) && $value=='Armenia') selected="true" @endif>  Armenia </option>
	<option value="Aruba" @if(isset($value) && $value=='Aruba') selected="true" @endif>  Aruba </option>
	<option value="ASEAN" @if(isset($value) && $value=='ASEAN') selected="true" @endif>  ASEAN </option>
	<option value="Australia" @if(isset($value) && $value=='Australia') selected="true" @endif>  Australia </option>
	<option value="Austria" @if(isset($value) && $value=='Austria') selected="true" @endif>  Austria </option>
	<option value="Azerbaijan" @if(isset($value) && $value=='Azerbaijan') selected="true" @endif> Azerbaijan  </option>
	<option value="Bahamas" @if(isset($value) && $value=='Bahamas') selected="true" @endif>  Bahamas </option>
	<option value="Bahrain" @if(isset($value) && $value=='Bahrain') selected="true" @endif>  Bahrain </option>
	<option value="Bangladesh" @if(isset($value) && $value=='Bangladesh') selected="true" @endif> Bangladesh  </option>
	<option value="Barbados" @if(isset($value) && $value=='Barbados') selected="true" @endif> Barbados  </option>
	<option value="Belarus" @if(isset($value) && $value=='Belarus') selected="true" @endif>  Belarus </option>
	<option value="Belgium" @if(isset($value) && $value=='Belgium') selected="true" @endif>  Belgium </option>
	<option value="Belize" @if(isset($value) && $value=='Belize') selected="true" @endif> Belize  </option>
	<option value="Benin" @if(isset($value) && $value=='Benin') selected="true" @endif>  Benin </option>
	<option value="Bermuda" @if(isset($value) && $value=='Bermuda') selected="true" @endif>  Bermuda </option>
	<option value="Bhutan" @if(isset($value) && $value=='Bhutan') selected="true" @endif> Bhutan  </option>
	<option value="Bolivia" @if(isset($value) && $value=='Bolivia') selected="true" @endif>  Bolivia </option>
	<option value="Bosnia-Herzegovina" @if(isset($value) && $value=='Bosnia-Herzegovina') selected="true" @endif> Bosnia-Herzegovina  </option>
	<option value="Botswana" @if(isset($value) && $value=='Botswana') selected="true" @endif> Botswana  </option>
	<option value="Brazil" @if(isset($value) && $value=='Brazil') selected="true" @endif> Brazil  </option>
	<option value="Brunei" @if(isset($value) && $value=='Brunei') selected="true" @endif> Brunei  </option>
	<option value="Bulgaria" @if(isset($value) && $value=='Bulgaria') selected="true" @endif> Bulgaria  </option>
	<option value="Burkina-Faso" @if(isset($value) && $value=='Burkina-Faso') selected="true" @endif> Burkina-Faso  </option>
	<option value="Burundi" @if(isset($value) && $value=='Burundi') selected="true" @endif>  Burundi </option>
	<option value="Cambodja" @if(isset($value) && $value=='Cambodja') selected="true" @endif> Cambodja  </option>
	<option value="Cameroon" @if(isset($value) && $value=='Cameroon') selected="true" @endif> Cameroon  </option>
	<option value="Canada" @if(isset($value) && $value=='Canada') selected="true" @endif> Canada  </option>
	<option value="Cape-Verde" @if(isset($value) && $value=='Cape-Verde') selected="true" @endif> Cape-Verde  </option>
	<option value="CARICOM" @if(isset($value) && $value=='CARICOM') selected="true" @endif>  CARICOM </option>
	<option value="Cayman-Islands" @if(isset($value) && $value=='Cayman-Islands') selected="true" @endif> Cayman-Islands  </option>
	<option value="Central-African-Republic" @if(isset($value) && $value=='Central-African-Republic') selected="true" @endif> Central-African-Republic  </option>
	<option value="Chad" @if(isset($value) && $value=='Chad') selected="true" @endif> Chad  </option>
	<option value="Chile" @if(isset($value) && $value=='Chile') selected="true" @endif>  Chile </option>
	<option value="China" @if(isset($value) && $value=='China') selected="true" @endif>  China </option>
	<option value="CIS" @if(isset($value) && $value=='CIS') selected="true" @endif>  CIS </option>
	<option value="Colombia" @if(isset($value) && $value=='Colombia') selected="true" @endif> Colombia  </option>
	<option value="Commonwealth" @if(isset($value) && $value=='Commonwealth') selected="true" @endif> Commonwealth  </option>
	<option value="Comoros" @if(isset($value) && $value=='Comoros') selected="true" @endif>  Comoros </option>
	<option value="Congo-Brazzaville" @if(isset($value) && $value=='Congo-Brazzaville') selected="true" @endif>  Congo-Brazzaville </option>
	<option value="Congo-Kinshasa(Zaire)" @if(isset($value) && $value=='Congo-Kinshasa(Zaire)') selected="true" @endif>  Congo-Kinshasa(Zaire) </option>
	<option value="Cook-Islands" @if(isset($value) && $value=='Cook-Islands') selected="true" @endif> Cook-Islands  </option>
	<option value="Costa-Rica" @if(isset($value) && $value=='Costa-Rica') selected="true" @endif> Costa-Rica  </option>
	<option value="Cote-d-Ivoire" @if(isset($value) && $value=='Cote-d-Ivoire') selected="true" @endif>  Cote-d-Ivoire </option>
	<option value="Croatia" @if(isset($value) && $value=='Croatia') selected="true" @endif>  Croatia </option>
	<option value="Cuba" @if(isset($value) && $value=='Cuba') selected="true" @endif> Cuba  </option>
	<option value="Cyprus" @if(isset($value) && $value=='Cyprus') selected="true" @endif> Cyprus  </option>
	<option value="Czech-Republic" @if(isset($value) && $value=='Czech-Republic') selected="true" @endif> Czech-Republic  </option>
	<option value="Denmark" @if(isset($value) && $value=='Denmark') selected="true" @endif>  Denmark </option>
	<option value="Djibouti" @if(isset($value) && $value=='Djibouti') selected="true" @endif> Djibouti  </option>
	<option value="Dominica" @if(isset($value) && $value=='Dominica') selected="true" @endif> Dominica  </option>
	<option value="Dominican-Republic" @if(isset($value) && $value=='Dominican-Republic') selected="true" @endif> Dominican-Republic  </option>
	<option value="Ecuador" @if(isset($value) && $value=='Ecuador') selected="true" @endif>  Ecuador </option>
	<option value="Egypt" @if(isset($value) && $value=='Egypt') selected="true" @endif>  Egypt </option>
	<option value="El-Salvador" @if(isset($value) && $value=='El-Salvador') selected="true" @endif>  El-Salvador </option>
	<option value="England" @if(isset($value) && $value=='England') selected="true" @endif>  England </option>
	<option value="Equatorial-Guinea" @if(isset($value) && $value=='Equatorial-Guinea') selected="true" @endif>  Equatorial-Guinea </option>
	<option value="Eritrea" @if(isset($value) && $value=='Eritrea') selected="true" @endif>  Eritrea </option>
	<option value="Estonia" @if(isset($value) && $value=='Estonia') selected="true" @endif>  Estonia </option>
	<option value="Ethiopia" @if(isset($value) && $value=='Ethiopia') selected="true" @endif> Ethiopia  </option>
	<option value="European-Union" @if(isset($value) && $value=='European-Union') selected="true" @endif> European-Union  </option>
	<option value="Faroes" @if(isset($value) && $value=='Faroes') selected="true" @endif> Faroes  </option>
	<option value="Fiji" @if(isset($value) && $value=='Fiji') selected="true" @endif> Fiji  </option>
	<option value="Finland" @if(isset($value) && $value=='Finland') selected="true" @endif>  Finland </option>
	<option value="France" @if(isset($value) && $value=='France') selected="true" @endif> France  </option>
	<option value="Gabon" @if(isset($value) && $value=='Gabon') selected="true" @endif>  Gabon </option>
	<option value="Gambia" @if(isset($value) && $value=='Gambia') selected="true" @endif> Gambia  </option>
	<option value="Georgia" @if(isset($value) && $value=='Georgia') selected="true" @endif>  Georgia </option>
	<option value="Germany" @if(isset($value) && $value=='Germany') selected="true" @endif>  Germany </option>
	<option value="Ghana" @if(isset($value) && $value=='Ghana') selected="true" @endif>  Ghana </option>
	<option value="Gibraltar" @if(isset($value) && $value=='Gibraltar') selected="true" @endif>  Gibraltar </option>
	<option value="Greece" @if(isset($value) && $value=='Greece') selected="true" @endif> Greece  </option>
	<option value="Greenland" @if(isset($value) && $value=='Greenland') selected="true" @endif>  Greenland </option>
	<option value="Grenada" @if(isset($value) && $value=='Grenada') selected="true" @endif>  Grenada </option>
	<option value="Guadeloupe" @if(isset($value) && $value=='Guadeloupe') selected="true" @endif> Guadeloupe  </option>
	<option value="Guam" @if(isset($value) && $value=='Guam') selected="true" @endif> Guam  </option>
	<option value="Guatemala" @if(isset($value) && $value=='Guatemala') selected="true" @endif>  Guatemala </option>
	<option value="Guernsey" @if(isset($value) && $value=='Guernsey') selected="true" @endif> Guernsey  </option>
	<option value="Guinea-Bissau" @if(isset($value) && $value=='Guinea-Bissau') selected="true" @endif>  Guinea-Bissau </option>
	<option value="Guinea" @if(isset($value) && $value=='Guinea') selected="true" @endif> Guinea  </option>
	<option value="Guyana" @if(isset($value) && $value=='Guyana') selected="true" @endif> Guyana  </option>
	<option value="Haiti" @if(isset($value) && $value=='Haiti') selected="true" @endif>  Haiti </option>
	<option value="Honduras" @if(isset($value) && $value=='Honduras') selected="true" @endif> Honduras  </option>
	<option value="Hong-Kong" @if(isset($value) && $value=='Hong-Kong') selected="true" @endif>  Hong-Kong </option>
	<option value="Hungary" @if(isset($value) && $value=='Hungary') selected="true" @endif>  Hungary </option>
	<option value="Iceland" @if(isset($value) && $value=='Iceland') selected="true" @endif>  Iceland </option>
	<option value="India" @if(isset($value) && $value=='India') selected="true" @endif>  India </option>
	<option value="Indonesia" @if(isset($value) && $value=='Indonesia') selected="true" @endif>  Indonesia </option>
	<option value="Iran" @if(isset($value) && $value=='Iran') selected="true" @endif> Iran  </option>
	<option value="Iraq" @if(isset($value) && $value=='Iraq') selected="true" @endif> Iraq  </option>
	<option value="Ireland" @if(isset($value) && $value=='Ireland') selected="true" @endif>  Ireland </option>
	<option value="Islamic-Conference" @if(isset($value) && $value=='Islamic-Conference') selected="true" @endif> Islamic-Conference  </option>
	<option value="Isle-of-Man" @if(isset($value) && $value=='Isle-of-Man') selected="true" @endif>  Isle-of-Man </option>
	<option value="Israel" @if(isset($value) && $value=='Israel') selected="true" @endif> Israel  </option>
	<option value="Italy" @if(isset($value) && $value=='Italy') selected="true" @endif>  Italy </option>
	<option value="Jamaica" @if(isset($value) && $value=='Jamaica') selected="true" @endif>  Jamaica </option>
	<option value="Japan" @if(isset($value) && $value=='Japan') selected="true" @endif>  Japan </option>
	<option value="Jersey" @if(isset($value) && $value=='Jersey') selected="true" @endif> Jersey  </option>
	<option value="Jordan" @if(isset($value) && $value=='Jordan') selected="true" @endif> Jordan  </option>
	<option value="Kazakhstan" @if(isset($value) && $value=='Kazakhstan') selected="true" @endif> Kazakhstan  </option>
	<option value="Kenya" @if(isset($value) && $value=='Kenya') selected="true" @endif>  Kenya </option>
	<option value="Kiribati" @if(isset($value) && $value=='Kiribati') selected="true" @endif> Kiribati  </option>
	<option value="Kosovo" @if(isset($value) && $value=='Kosovo') selected="true" @endif> Kosovo  </option>
	<option value="Kuwait" @if(isset($value) && $value=='Kuwait') selected="true" @endif> Kuwait  </option>
	<option value="Kyrgyzstan" @if(isset($value) && $value=='Kyrgyzstan') selected="true" @endif> Kyrgyzstan  </option>
	<option value="Laos" @if(isset($value) && $value=='Laos') selected="true" @endif> Laos  </option>
	<option value="Latvia" @if(isset($value) && $value=='Latvia') selected="true" @endif> Latvia  </option>
	<option value="Lebanon" @if(isset($value) && $value=='Lebanon') selected="true" @endif>  Lebanon </option>
	<option value="Lesotho" @if(isset($value) && $value=='Lesotho') selected="true" @endif>  Lesotho </option>
	<option value="Liberia" @if(isset($value) && $value=='Liberia') selected="true" @endif>  Liberia </option>
	<option value="Libya" @if(isset($value) && $value=='Libya') selected="true" @endif>  Libya </option>
	<option value="Liechtenstein" @if(isset($value) && $value=='Liechtenstein') selected="true" @endif>  Liechtenstein </option>
	<option value="LIthuania" @if(isset($value) && $value=='LIthuania') selected="true" @endif>  LIthuania </option>
	<option value="Luxembourg" @if(isset($value) && $value=='Luxembourg') selected="true" @endif> Luxembourg  </option>
	<option value="Macao" @if(isset($value) && $value=='Macao') selected="true" @endif>  Macao </option>
	<option value="Macedonia" @if(isset($value) && $value=='Macedonia') selected="true" @endif>  Macedonia </option>
	<option value="Madagascar" @if(isset($value) && $value=='Madagascar') selected="true" @endif> Madagascar  </option>
	<option value="Malawi" @if(isset($value) && $value=='Malawi') selected="true" @endif> Malawi  </option>
	<option value="Malaysia" @if(isset($value) && $value=='Malaysia') selected="true" @endif> Malaysia  </option>
	<option value="Maldives" @if(isset($value) && $value=='Maldives') selected="true" @endif> Maldives  </option>
	<option value="Mali" @if(isset($value) && $value=='Mali') selected="true" @endif> Mali  </option>
	<option value="Malta" @if(isset($value) && $value=='Malta') selected="true" @endif>  Malta </option>
	<option value="Marshall-Islands" @if(isset($value) && $value=='Marshall-Islands') selected="true" @endif> Marshall-Islands  </option>
	<option value="Martinique" @if(isset($value) && $value=='Martinique') selected="true" @endif> Martinique  </option>
	<option value="Mauritania" @if(isset($value) && $value=='Mauritania') selected="true" @endif> Mauritania  </option>
	<option value="Mauritius" @if(isset($value) && $value=='Mauritius') selected="true" @endif>  Mauritius </option>
	<option value="Mexico" @if(isset($value) && $value=='Mexico') selected="true" @endif> Mexico  </option>
	<option value="Micronesia" @if(isset($value) && $value=='Micronesia') selected="true" @endif> Micronesia  </option>
	<option value="Moldova" @if(isset($value) && $value=='Moldova') selected="true" @endif>  Moldova </option>
	<option value="Monaco" @if(isset($value) && $value=='Monaco') selected="true" @endif> Monaco  </option>
	<option value="Mongolia" @if(isset($value) && $value=='Mongolia') selected="true" @endif> Mongolia  </option>
	<option value="Montenegro" @if(isset($value) && $value=='Montenegro') selected="true" @endif> Montenegro  </option>
	<option value="Montserrat" @if(isset($value) && $value=='Montserrat') selected="true" @endif> Montserrat  </option>
	<option value="Morocco" @if(isset($value) && $value=='Morocco') selected="true" @endif>  Morocco </option>
	<option value="Mozambique" @if(isset($value) && $value=='Mozambique') selected="true" @endif> Mozambique  </option>
	<option value="Myanmar(Burma)" @if(isset($value) && $value=='Myanmar(Burma)') selected="true" @endif> Myanmar(Burma)  </option>
	<option value="Namibia" @if(isset($value) && $value=='Namibia') selected="true" @endif>  Namibia </option>
	<option value="NATO" @if(isset($value) && $value=='NATO') selected="true" @endif> NATO  </option>
	<option value="Nauru" @if(isset($value) && $value=='Nauru') selected="true" @endif>  Nauru </option>
	<option value="Nepal" @if(isset($value) && $value=='Nepal') selected="true" @endif>  Nepal </option>
	<option value="Netherlands-Antilles" @if(isset($value) && $value=='Netherlands-Antilles') selected="true" @endif> Netherlands-Antilles  </option>
	<option value="Netherlands" @if(isset($value) && $value=='Netherlands') selected="true" @endif>  Netherlands </option>
	<option value="New-Caledonia" @if(isset($value) && $value=='New-Caledonia') selected="true" @endif>  New-Caledonia </option>
	<option value="New-Zealand" @if(isset($value) && $value=='New-Zealand') selected="true" @endif>  New-Zealand </option>
	<option value="Nicaragua" @if(isset($value) && $value=='Nicaragua') selected="true" @endif>  Nicaragua </option>
	<option value="Niger" @if(isset($value) && $value=='Niger') selected="true" @endif>  Niger </option>
	<option value="Nigeria" @if(isset($value) && $value=='Nigeria') selected="true" @endif>  Nigeria </option>
	<option value="North-Korea" @if(isset($value) && $value=='North-Korea') selected="true" @endif>  North-Korea </option>
	<option value="Northern-Cyprus" @if(isset($value) && $value=='Northern-Cyprus') selected="true" @endif>  Northern-Cyprus </option>
	<option value="Northern-Ireland" @if(isset($value) && $value=='Northern-Ireland') selected="true" @endif> Northern-Ireland  </option>
	<option value="Norway" @if(isset($value) && $value=='Norway') selected="true" @endif> Norway  </option>
	<option value="Olimpic-Movement" @if(isset($value) && $value=='Olimpic-Movement') selected="true" @endif> Olimpic-Movement  </option>
	<option value="Oman" @if(isset($value) && $value=='Oman') selected="true" @endif> Oman  </option>
	<option value="OPEC" @if(isset($value) && $value=='OPEC') selected="true" @endif> OPEC  </option>
	<option value="Pakistan" @if(isset($value) && $value=='Pakistan') selected="true" @endif> Pakistan  </option>
	<option value="Palau" @if(isset($value) && $value=='Palau') selected="true" @endif>  Palau </option>
	<option value="Palestine" @if(isset($value) && $value=='Palestine') selected="true" @endif>  Palestine </option>
	<option value="Panama" @if(isset($value) && $value=='Panama') selected="true" @endif> Panama  </option>
	<option value="Papua-New-Guinea" @if(isset($value) && $value=='Papua-New-Guinea') selected="true" @endif> Papua-New-Guinea  </option>
	<option value="Paraguay" @if(isset($value) && $value=='Paraguay') selected="true" @endif> Paraguay  </option>
	<option value="Peru" @if(isset($value) && $value=='Peru') selected="true" @endif> Peru  </option>
	<option value="Philippines" @if(isset($value) && $value=='Philippines') selected="true" @endif>  Philippines </option>
	<option value="Poland" @if(isset($value) && $value=='Poland') selected="true" @endif> Poland  </option>
	<option value="Portugal" @if(isset($value) && $value=='Portugal') selected="true" @endif> Portugal  </option>
	<option value="Puerto-Rico" @if(isset($value) && $value=='Puerto-Rico') selected="true" @endif>  Puerto-Rico </option>
	<option value="Qatar" @if(isset($value) && $value=='Qatar') selected="true" @endif>  Qatar </option>
	<option value="Red-Cross" @if(isset($value) && $value=='Red-Cross') selected="true" @endif>  Red-Cross </option>
	<option value="Reunion" @if(isset($value) && $value=='Reunion') selected="true" @endif>  Reunion </option>
	<option value="Romania" @if(isset($value) && $value=='Romania') selected="true" @endif>  Romania </option>
	<option value="Russian-Federation" @if(isset($value) && $value=='Russian-Federation') selected="true" @endif> Russian-Federation  </option>
	<option value="Rwanda" @if(isset($value) && $value=='Rwanda') selected="true" @endif> Rwanda  </option>
	<option value="Saint-Lucia" @if(isset($value) && $value=='Saint-Lucia') selected="true" @endif>  Saint-Lucia </option>
	<option value="Samoa" @if(isset($value) && $value=='Samoa') selected="true" @endif>  Samoa </option>
	<option value="San-Marino" @if(isset($value) && $value=='San-Marino') selected="true" @endif> San-Marino  </option>
	<option value="Sao-Tome-Principe" @if(isset($value) && $value=='Sao-Tome-Principe') selected="true" @endif>  Sao-Tome-Principe </option>
	<option value="Saudi-Arabia" @if(isset($value) && $value=='Saudi-Arabia') selected="true" @endif> Saudi-Arabia  </option>
	<option value="Scotland" @if(isset($value) && $value=='Scotland') selected="true" @endif> Scotland  </option>
	<option value="Senegal" @if(isset($value) && $value=='Senegal') selected="true" @endif>  Senegal </option>
	<option value="Serbia(Yugoslavia)" @if(isset($value) && $value=='Serbia(Yugoslavia)') selected="true" @endif> Serbia(Yugoslavia)  </option>
	<option value="Seychelles" @if(isset($value) && $value=='Seychelles') selected="true" @endif> Seychelles  </option>
	<option value="Sierra-Leone" @if(isset($value) && $value=='Sierra-Leone') selected="true" @endif> Sierra-Leone  </option>
	<option value="Singapore" @if(isset($value) && $value=='Singapore') selected="true" @endif>  Singapore </option>
	<option value="Slovakia" @if(isset($value) && $value=='Slovakia') selected="true" @endif> Slovakia  </option>
	<option value="Slovenia" @if(isset($value) && $value=='Slovenia') selected="true" @endif> Slovenia  </option>
	<option value="Solomon-Islands" @if(isset($value) && $value=='Solomon-Islands') selected="true" @endif>  Solomon-Islands </option>
	<option value="Somalia" @if(isset($value) && $value=='Somalia') selected="true" @endif>  Somalia </option>
	<option value="Somaliland" @if(isset($value) && $value=='Somaliland') selected="true" @endif> Somaliland  </option>
	<option value="South-Africa" @if(isset($value) && $value=='South-Africa') selected="true" @endif> South-Africa  </option>
	<option value="South-Korea" @if(isset($value) && $value=='South-Korea') selected="true" @endif>  South-Korea </option>
	<option value="Spain" @if(isset($value) && $value=='Spain') selected="true" @endif>  Spain </option>
	<option value="Sri-Lanka" @if(isset($value) && $value=='Sri-Lanka') selected="true" @endif>  Sri-Lanka </option>
	<option value="St-Kitts-Nevis" @if(isset($value) && $value=='St-Kitts-Nevis') selected="true" @endif> St-Kitts-Nevis  </option>
	<option value="St-Vincent-the-Grenadines" @if(isset($value) && $value=='St-Vincent-the-Grenadines') selected="true" @endif>  St-Vincent-the-Grenadines </option>
	<option value="Sudan" @if(isset($value) && $value=='Sudan') selected="true" @endif>  Sudan </option>
	<option value="Suriname" @if(isset($value) && $value=='Suriname') selected="true" @endif> Suriname  </option>
	<option value="Swaziland" @if(isset($value) && $value=='Swaziland') selected="true" @endif>  Swaziland </option>
	<option value="Sweden" @if(isset($value) && $value=='Sweden') selected="true" @endif> Sweden  </option>
	<option value="Switzerland" @if(isset($value) && $value=='Switzerland') selected="true" @endif>  Switzerland </option>
	<option value="Syria" @if(isset($value) && $value=='Syria') selected="true" @endif>  Syria </option>
	<option value="Tahiti(French-Polinesia)" @if(isset($value) && $value=='Tahiti(French-Polinesia)') selected="true" @endif> Tahiti(French-Polinesia)  </option>
	<option value="Taiwan" @if(isset($value) && $value=='Taiwan') selected="true" @endif> Taiwan  </option>
	<option value="Tajikistan" @if(isset($value) && $value=='Tajikistan') selected="true" @endif> Tajikistan  </option>
	<option value="Tanzania" @if(isset($value) && $value=='Tanzania') selected="true" @endif> Tanzania  </option>
	<option value="Thailand" @if(isset($value) && $value=='Thailand') selected="true" @endif> Thailand  </option>
	<option value="Timor-Leste" @if(isset($value) && $value=='Timor-Leste') selected="true" @endif>  Timor-Leste </option>
	<option value="Togo" @if(isset($value) && $value=='Togo') selected="true" @endif> Togo  </option>
	<option value="Tonga" @if(isset($value) && $value=='Tonga') selected="true" @endif>  Tonga </option>
	<option value="Trinidad-Tobago" @if(isset($value) && $value=='Trinidad-Tobago') selected="true" @endif>  Trinidad-Tobago </option>
	<option value="Tunisia" @if(isset($value) && $value=='Tunisia') selected="true" @endif>  Tunisia </option>
	<option value="Turkey" @if(isset($value) && $value=='Turkey') selected="true" @endif> Turkey  </option>
	<option value="Turkmenistan" @if(isset($value) && $value=='Turkmenistan') selected="true" @endif> Turkmenistan  </option>
	<option value="Turks-and-Caicos-Islands" @if(isset($value) && $value=='Turks-and-Caicos-Islands') selected="true" @endif> Turks-and-Caicos-Islands  </option>
	<option value="Tuvalu" @if(isset($value) && $value=='Tuvalu') selected="true" @endif> Tuvalu  </option>
	<option value="Uganda" @if(isset($value) && $value=='Uganda') selected="true" @endif> Uganda  </option>
	<option value="Ukraine" @if(isset($value) && $value=='Ukraine') selected="true" @endif>  Ukraine </option>
	<option value="United-Arab-Emirates" @if(isset($value) && $value=='United-Arab-Emirates') selected="true" @endif> United-Arab-Emirates  </option>
	<option value="United-Kingdom(Great-Britain)" @if(isset($value) && $value=='United-Kingdom(Great-Britain)') selected="true" @endif>  United-Kingdom(Great-Britain) </option>
	<option value="United-Nations" @if(isset($value) && $value=='United-Nations') selected="true" @endif> United-Nations  </option>
	<option value="United-States-of-America-(USA)" @if(isset($value) && $value=='United-States-of-America-(USA)') selected="true" @endif> United-States-of-America-(USA)  </option>
	<option value="Uruguay" @if(isset($value) && $value=='Uruguay') selected="true" @endif>  Uruguay </option>
</select>